Master Run builds, tests, and releases now
The Master run is able to:
- build sac2c
- run unit-tests on sac2c
- build stdlib
- create distributable packages of sac2c and stdlib
- release the packages to SaC homepage

The last two stages are only activated on a schedule event. As such,
for merge requests we build, test, and build stdlib. The entire process
takes about 1 to 1:15 hours to do.

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -1,30 +1,155 @@
-# This is the CI/build script for the GitLab-CI system for building/testing
+# This is the CI/build config for the GitLab-CI system for building/testing
 # the SaC compiler
 
-# we'll likely need to ensure that basic build tools are available
-#before_script:
-
-# here we define specific groups of actions (which are run in parallel)
+# The first half of this file defines a series of templates for the primary
+# pipeline stages:
 stages:
-    - build
-    - package
+    - build   # the omnibus (debug + release versions) of the compiler
+    - test    # run unit-tests
+    - stdlib  # build the stdlib
+    - package # package both sac2c and stdlib       - only through schedule
+    - release # deploy the packages to sac-home.org - only through schedule
 
-build-archlinux:
+# The templates are generic enough that they are applicable on *all* build
+# OSs (it is assumed that various tools and commands are the same across
+# the board - if this is not the case things may need to be changed).
+
+# TODO (hans) Trigger variables
+#  - to build *only* sac2c: BUILD_SAC2C must be set,
+#  - to build *only* stdlib: BUILD_STDLIB must be set,
+#  - to build all: _set *both* above_
+#  - to deploy packages: DO_RELEASE must be set
+
+# here we define specific templates for various actions:
+
+.build-template: &build-template
     stage: build
     # here we define the commands to run
     script:
         - mkdir $HOME/.sac2crc
         - mkdir build && cd build
         - cmake ../cmake/cpack
-        - make -j2
-    # ensure that we build on the correct docker container (there should
-    # only be one tag listed below!)
-    tags:
-        - archlinux
+        - make -j2 2>&1 | tee build.log
+        # TODO does not error yet (testing)...
+        - if [ $(grep -i 'warning' build.log | wc -l) -gt 0 ]; then
+          echo "+++ ${WARN_NUM} warnings detected +++";
+          grep -i 'warning' build.log;
+          fi
+        # we need to store the .sac2crc file for sac2c to find prelude
+        - mv $HOME/.sac2crc $PWD
     # ensure we capture the build blob
     artifacts:
         expire_in: 12 hrs
         untracked: true
+
+.test-template: &test-template
+    stage: test
+    script:
+        - cp -r build/.sac2crc $HOME
+        - cd build
+        - make fulltest
+    artifacts:
+        expire_in: 12 hrs
+        untracked: true
+
+.build-stdlib-template: &build-stdlib-template
+    stage: stdlib
+    variables:
+        SAC2CP_EXEC: "${CI_PROJECT_DIR}/build/sac2c-release/src/sac2c-release-build/sac2c_p"
+        SAC2CD_EXEC: "${CI_PROJECT_DIR}/build/sac2c-debug/src/sac2c-debug-build/sac2c_d"
+    script:
+        - cp -r build/.sac2crc $HOME
+        # get latest release of stdlib
+        # XXX would be nice if we could use `--single-branch`, as it would
+        # save on bandwidth + time. But some OSs don't have > git 1.7 (?!)
+        - git clone https://github.com/SacBase/Stdlib.git stdlib
+        - cd stdlib
+        - git submodule init
+        - git submodule update
+        - cd ..
+        - mkdir stdlib-build && cd stdlib-build
+        - cmake -DSAC2C_EXEC=${SAC2CP_EXEC} ../stdlib
+        - make -j2 2>&1 | tee build.log
+        # TODO does not error yet (testing)...
+        - if [ $(grep -i 'warning' build.log | wc -l) -gt 0 ]; then
+          echo "+++ ${WARN_NUM} warnings detected +++";
+          grep -i 'warning' build.log;
+          fi
+        # capture new sac2crcs
+        - mv -f $HOME/.sac2crc ${CI_PROJECT_DIR}/build/.sac2crc
+    # ensure we capture the build blob
+    artifacts:
+        expire_in: 12 hrs
+        untracked: true
+        paths:
+            - stdlib/
+
+.package-template: &package-template
+    stage: package
+    script:
+        - cp -r build/.sac2crc $HOME
+        - cd build
+        - cpack -G ${CPACK_BUILD}
+        - cd ../stdlib-build
+        - cpack -G ${CPACK_BUILD}
+    artifacts:
+        expire_in: 4 hrs
+        paths:
+            - build/${RELEASE_FILE}
+            - stdlib-build/${RELEASE_FILE}
+
+.weekly-release-template: &weekly-release-template
+    stage: release
+    script:
+        # skip if we don't want to ship the release
+        - if [ ! -d ${HOME}/.ssh ]; then mkdir ${HOME}/.ssh; fi
+        - chmod 700 ${HOME}/.ssh
+        - echo "${SSH_RELEASE_KEY}" > $HOME/.ssh/release
+        - chmod 600 ${HOME}/.ssh/release
+        - if [ ! -d build ] || [ ! -d stdlib-build ]; then echo "Unable to find artifacts"; exit 1; fi
+        - scp -p -i ${HOME}/.ssh/release -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no
+          build/${RELEASE_FILE} stdlib-build/${RELEASE_FILE} ${RELEASE_URL}:${RELEASE_TOPDIR}/${INNER_PATH}
+        - echo "Release has been sent, have a look at the sac-home.org download page :)"
+
+# Here we define the actual jobs - we must specify each build OS separately as GitLab-CI
+# does not support launch a job on all OSs as such.
+
+### ARCHLINUX ###
+
+build-archlinux:
+    <<: *build-template
+    # ensure that we build on the correct docker container (there should
+    # only be one tag listed below!)
+    tags:
+        - archlinux
+    only:
+        # we use the trigger mechanism as this is currently the only
+        # feasible way of actually having stuff build via merge-requests.
+        - triggers
+        - schedules
+        - web
+
+test-archlinux:
+    <<: *test-template
+    # ensure that we build on the correct docker container (there should
+    # only be one tag listed below!)
+    tags:
+        - archlinux
+    dependencies:
+        - build-archlinux
+    only:
+        # we use the trigger mechanism as this is currently the only
+        # feasible way of actually having stuff build via merge-requests.
+        - triggers
+        - schedules
+        - web
+
+stdlib-archlinux:
+    <<: *build-stdlib-template
+    tags:
+        - archlinux
+    dependencies:
+        - test-archlinux
     only:
         # we use the trigger mechanism as this is currently the only
         # feasible way of actually having stuff build via merge-requests.
@@ -33,173 +158,258 @@ build-archlinux:
         - web
 
 package-archlinux:
-    stage: package
-    script:
-        - mkdir $HOME/.sac2crc
-        - cd build
-        - cpack -G TGZ
+    variables:
+        CPACK_BUILD: "TGZ"
+        RELEASE_FILE: "*.tar.gz"
+    <<: *package-template
     tags:
         - archlinux
-    artifacts:
-        expire_in: 4 weeks
-        paths:
-            - build/*.tar.gz
     dependencies:
-        - build-archlinux
+        - stdlib-archlinux
     only:
+        - schedules
+
+release-weekly-archlinux:
+    variables:
+        INNER_PATH: "TGZ-weekly/Linux"
+        RELEASE_FILE: "*.tar.gz"
+        GIT_STRATEGY: none
+    <<: *weekly-release-template
+    tags:
+        - archlinux
+    dependencies:
+        - package-archlinux
+    only:
+        - schedules
+
+### CENTOS 7 ###
+
+build-centos7:
+    <<: *build-template
+    tags:
+        - centos7
+    only:
+        - triggers
         - schedules
         - web
 
-build-centos7:
-    stage: build
-    # here we define the commands to run
-    script:
-        - mkdir $HOME/.sac2crc
-        - mkdir build && cd build
-        - cmake3 ../cmake/cpack
-        - make -j2
-    # ensure that we build on the correct docker container (there should
-    # only be one tag listed below!)
+test-centos7:
+    <<: *test-template
     tags:
         - centos7
-    # ensure we capture the build blob
-    artifacts:
-        expire_in: 12 hrs
-        untracked: true
+    dependencies:
+        - build-centos7
+    only:
+        - triggers
+        - schedules
+        - web
+
+stdlib-centos7:
+    <<: *build-stdlib-template
+    tags:
+        - centos7
+    dependencies:
+        - test-centos7
     only:
         - triggers
         - schedules
         - web
 
 package-centos7:
-    stage: package
-    script:
-        - mkdir $HOME/.sac2crc
-        - cd build
-        - cpack3 -G RPM
+    variables:
+        CPACK_BUILD: "RPM"
+        RELEASE_FILE: "*.rpm"
+    <<: *package-template
     tags:
         - centos7
-    artifacts:
-        expire_in: 4 weeks
-        paths:
-            - build/*.rpm
     dependencies:
-        - build-centos7
+        - stdlib-centos7
     only:
+        - schedules
+
+release-weekly-centos7:
+    variables:
+        INNER_PATH: "RPM-weekly/RHEL7"
+        RELEASE_FILE: "*.rpm"
+        GIT_STRATEGY: none
+    <<: *weekly-release-template
+    tags:
+        - centos7
+    dependencies:
+        - package-centos7
+    only:
+        - schedules
+
+### CENTOS 6 ###
+
+build-centos6:
+    <<: *build-template
+    tags:
+        - centos6
+    only:
+        - triggers
         - schedules
         - web
 
-build-centos6:
-    stage: build
-    # here we define the commands to run
-    script:
-        - mkdir $HOME/.sac2crc
-        - mkdir build && cd build
-        - cmake ../cmake/cpack
-        - make -j2
-    # ensure that we build on the correct docker container (there should
-    # only be one tag listed below!)
+test-centos6:
+    <<: *test-template
     tags:
         - centos6
-    # ensure we capture the build blob
-    artifacts:
-        expire_in: 12 hrs
-        untracked: true
+    dependencies:
+        - build-centos6
     only:
+        - triggers
+        - schedules
+        - web
+
+stdlib-centos6:
+    <<: *build-stdlib-template
+    tags:
+        - centos6
+    dependencies:
+        - test-centos6
+    only:
+        - triggers
         - schedules
         - web
 
 package-centos6:
-    stage: package
-    script:
-        - mkdir $HOME/.sac2crc
-        - cd build
-        - cpack -G RPM
+    variables:
+        CPACK_BUILD: "RPM"
+        RELEASE_FILE: "*.rpm"
+    <<: *package-template
     tags:
         - centos6
-    artifacts:
-        expire_in: 4 weeks
-        paths:
-            - build/*.rpm
     dependencies:
-        - build-centos6
+        - stdlib-centos6
     only:
+        - schedules
+
+release-weekly-centos6:
+    variables:
+        INNER_PATH: "RPM-weekly/RHEL6"
+        RELEASE_FILE: "*.rpm"
+        GIT_STRATEGY: none
+    <<: *weekly-release-template
+    tags:
+        - centos6
+    dependencies:
+        - package-centos6
+    only:
+        - schedules
+
+### UBUNTU 16 ###
+
+build-ubuntu16:
+    <<: *build-template
+    tags:
+        - ubuntu16
+    only:
+        - triggers
         - schedules
         - web
 
-build-ubuntu16:
-    stage: build
-    # here we define the commands to run
-    script:
-        - mkdir $HOME/.sac2crc
-        - mkdir build && cd build
-        - cmake ../cmake/cpack
-        - make -j2
-    # ensure that we build on the correct docker container (there should
-    # only be one tag listed below!)
+test-ubuntu16:
+    <<: *test-template
     tags:
         - ubuntu16
-    # ensure we capture the build blob
-    artifacts:
-        expire_in: 12 hrs
-        untracked: true
+    dependencies:
+        - build-ubuntu16
+    only:
+        - triggers
+        - schedules
+        - web
+
+stdlib-ubuntu16:
+    <<: *build-stdlib-template
+    tags:
+        - ubuntu16
+    dependencies:
+        - test-ubuntu16
     only:
         - triggers
         - schedules
         - web
 
 package-ubuntu16:
-    stage: package
-    script:
-        - mkdir $HOME/.sac2crc
-        - cd build
-        - cpack -G DEB
+    variables:
+        CPACK_BUILD: "DEB"
+        RELEASE_FILE: "*.deb"
+    <<: *package-template
     tags:
         - ubuntu16
-    artifacts:
-        expire_in: 4 weeks
-        paths:
-            - build/*.deb
     dependencies:
-        - build-ubuntu16
+        - stdlib-ubuntu16
     only:
+        - schedules
+
+release-weekly-ubuntu16:
+    variables:
+        INNER_PATH: "DEB-weekly/Ubl16"
+        RELEASE_FILE: "*.deb"
+        GIT_STRATEGY: none
+    <<: *weekly-release-template
+    tags:
+        - ubuntu16
+    dependencies:
+        - package-ubuntu16
+    only:
+        - schedules
+
+### UBUNTU 14 ###
+
+build-ubuntu14:
+    <<: *build-template
+    tags:
+        - ubuntu14
+    only:
+        - triggers
         - schedules
         - web
 
-build-ubuntu14:
-    stage: build
-    # here we define the commands to run
-    script:
-        - mkdir $HOME/.sac2crc
-        - mkdir build && cd build
-        - cmake ../cmake/cpack
-        - make -j2
-    # ensure that we build on the correct docker container (there should
-    # only be one tag listed below!)
+test-ubuntu14:
+    <<: *test-template
     tags:
         - ubuntu14
-    # ensure we capture the build blob
-    artifacts:
-        expire_in: 12 hrs
-        untracked: true
+    dependencies:
+        - build-ubuntu14
     only:
+        - triggers
+        - schedules
+        - web
+
+stdlib-ubuntu14:
+    <<: *build-stdlib-template
+    tags:
+        - ubuntu14
+    dependencies:
+        - test-ubuntu14
+    only:
+        - triggers
         - schedules
         - web
 
 package-ubuntu14:
-    stage: package
-    script:
-        - mkdir $HOME/.sac2crc
-        - cd build
-        - cpack -G DEB
+    variables:
+        CPACK_BUILD: "DEB"
+        RELEASE_FILE: "*.deb"
+    <<: *package-template
     tags:
         - ubuntu14
-    artifacts:
-        expire_in: 4 weeks
-        paths:
-            - build/*.deb
     dependencies:
-        - build-ubuntu14
+        - stdlib-ubuntu14
     only:
         - schedules
-        - web
+
+release-weekly-ubuntu14:
+    variables:
+        INNER_PATH: "DEB-weekly/Ubl14"
+        RELEASE_FILE: "*.deb"
+        GIT_STRATEGY: none
+    <<: *weekly-release-template
+    tags:
+        - ubuntu14
+    dependencies:
+        - package-ubuntu14
+    only:
+        - schedules
