fixed bison/yacc test

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -2686,9 +2686,52 @@ echo $ECHO_N "checking whether $YACC works... $ECHO_C" >&6
     echo "$as_me:$LINENO: result: ok" >&5
 echo "${ECHO_T}ok" >&6
   else
-    YACC=yacc
     echo "$as_me:$LINENO: result: failed" >&5
 echo "${ECHO_T}failed" >&6
+    # Extract the first word of "yacc", so it can be a program name with args.
+set dummy yacc; ac_word=$2
+echo "$as_me:$LINENO: checking for $ac_word" >&5
+echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6
+if test "${ac_cv_prog_YACC+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  if test -n "$YACC"; then
+  ac_cv_prog_YACC="$YACC" # Let the user override the test.
+else
+as_save_IFS=$IFS; IFS=$PATH_SEPARATOR
+for as_dir in $PATH
+do
+  IFS=$as_save_IFS
+  test -z "$as_dir" && as_dir=.
+  for ac_exec_ext in '' $ac_executable_extensions; do
+  if $as_executable_p "$as_dir/$ac_word$ac_exec_ext"; then
+    ac_cv_prog_YACC="yacc"
+    echo "$as_me:$LINENO: found $as_dir/$ac_word$ac_exec_ext" >&5
+    break 2
+  fi
+done
+done
+
+  test -z "$ac_cv_prog_YACC" && ac_cv_prog_YACC="!fail"
+fi
+fi
+YACC=$ac_cv_prog_YACC
+if test -n "$YACC"; then
+  echo "$as_me:$LINENO: result: $YACC" >&5
+echo "${ECHO_T}$YACC" >&6
+else
+  echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
+fi
+
+    if  test "$YACC" != "yacc" ; then
+      { { echo "$as_me:$LINENO: error: cannot find working bison/yacc" >&5
+echo "$as_me: error: cannot find working bison/yacc" >&2;}
+   { (exit 10); exit 10; }; }
+    else
+      { echo "$as_me:$LINENO: using yacc instead" >&5
+echo "$as_me: using yacc instead" >&6;}
+    fi
   fi
   cd ..
   rm -rf .ac_yacc_test
