OSF_ALPHA added

diff --git a/distrib/src/Makefile b/distrib/src/Makefile
--- a/distrib/src/Makefile
+++ b/distrib/src/Makefile
@@ -1,5 +1,8 @@
 #
 # $Log$
+# Revision 2.4  2000/11/14 16:29:35  dkr
+# OSF_ALPHA added
+#
 # Revision 2.3  2000/04/27 15:44:51  cg
 # Makefile for binary SAC distributions now handles multipart
 # SAC runtime libraries for Solaris as well as Linux.
@@ -37,7 +40,7 @@ VERSION    =  0_9
 #  Settings for file and package sets
 #
 
-SYSTEMS    =  SOLARIS_SPARC LINUX_X86
+SYSTEMS    =  SOLARIS_SPARC LINUX_X86 OSF_ALPHA
 PACKAGES   =  runtime.tar stdlib.tar demo.tar
 FILES      =  install_sac LICENSE README
 SPECIFICS  =  sac2c libsac.tar sac2crc
@@ -73,10 +76,20 @@ SOLARIS_DIR   =  /var/tmp/$(USER)_sac_distrib
 #  Settings for system LINUX_X86
 #
 
-LX86_HOST  =  fafnir
+LX86_HOST  =  bunasera
 LX86_USER  =  sac
 LX86_DIR   =  sac_distrib
 LX86_MAKE  =  make
+
+
+#
+#  Settings for system OSF_ALPHA
+#
+
+ALPHA_HOST  =  scalar03.rz
+ALPHA_USER  =  sunip112
+ALPHA_DIR   =  sac_distrib
+ALPHA_MAKE  =  gmake
 
 
 #
@@ -90,7 +103,7 @@ CHECKFILES    :=  $(PACKAGES) $(foreach system,$(SYSTEMS), $(addsuffix .for.$(sy
 
 
 
-.PHONY: all linux solaris source clean update new allnew check_existing_files 
+.PHONY: all linux solaris alpha source clean update new allnew check_existing_files
 
 
 all: check_existing_files $(BINDISTRIBS) $(SRCDISTRIBS)
@@ -98,6 +111,8 @@ all: check_existing_files $(BINDISTRIBS) $(SRCDISTRIBS)
 linux: check_existing_files $(BINTARGETDIR)/SAC-$(VERSION)-LINUX_X86-$(DATE).tar.gz
 
 solaris: check_existing_files $(BINTARGETDIR)/SAC-$(VERSION)-SOLARIS_SPARC-$(DATE).tar.gz
+
+alpha: check_existing_files $(BINTARGETDIR)/SAC-$(VERSION)-OSF_ALPHA-$(DATE).tar.gz
 
 source: check_existing_files $(SRCTARGETDIR)/SAC-$(VERSION)-$(DATE).tar.gz
 
@@ -122,6 +137,7 @@ sac2c.for.SOLARIS_SPARC libsac.tar.for.SOLARIS_SPARC:
 	cp $(SAC2CDIR)/src.tar.gz $(SOLARIS_DIR)
 	(cd $(SOLARIS_DIR); gunzip -f src.tar.gz)
 	(cd $(SOLARIS_DIR); tar xvf src.tar)
+	(cd $(SOLARIS_DIR); make deps)
 	(cd $(SOLARIS_DIR); $(MAKE) distrib_product OS=SOLARIS_SPARC)
 	cp $(SOLARIS_DIR)/sac2c sac2c.for.SOLARIS_SPARC
 	(cd $(SOLARIS_DIR)/src/runtime; tar cvfh libsac.tar libsac*.a) 
@@ -148,23 +164,59 @@ sac2c.for.LINUX_X86 libsac.tar.for.LINUX_X86:
 	rsh -l $(LX86_USER) $(LX86_HOST) 'rm -rf $(LX86_DIR); mkdir -p $(LX86_DIR)' 
 	rcp $(SAC2CDIR)/src.tar.gz $(LX86_USER)@$(LX86_HOST):$(LX86_DIR)
 	rsh -l $(LX86_USER) $(LX86_HOST) \
-	    'cd $(LX86_DIR);'  \
+	    'cd $(LX86_DIR);'        \
 	    'gunzip -f src.tar.gz;'  \
-	    'tar xvf src.tar;'  \
-	    '$(LX86_MAKE) deps;' \
+	    'tar xvf src.tar;'       \
+	    'chmod -R u+w *;'        \
+	    'touch src/*/*;'         \
+	    '$(LX86_MAKE) deps;'     \
 	    '$(LX86_MAKE) distrib_product OS=LINUX_X86'
 	rcp $(LX86_USER)@$(LX86_HOST):$(LX86_DIR)/sac2c ./sac2c.for.LINUX_X86
-	rsh -l $(LX86_USER) $(LX86_HOST) \
+	rsh -l $(LX86_USER) $(LX86_HOST)   \
 	    'cd $(LX86_DIR)/src/runtime;'  \
 	    'tar cvfh libsac.tar libsac*.a'
 	rcp $(LX86_USER)@$(LX86_HOST):$(LX86_DIR)/src/runtime/libsac.tar ./libsac.tar.for.LINUX_X86
 	@ if [ $${?} -eq 0 ]; then  \
-            rsh -l $(LX86_USER) $(LX86_HOST) 'rm -rf $(LX86_DIR)'; \
-          else \
-            echo "Compilation of sac2c for LINUX_X86 failed!"; \
-            echo "Unable to create LINUX_X86 distribution !"; \
+	    rsh -l $(LX86_USER) $(LX86_HOST) 'rm -rf $(LX86_DIR)'; \
+	  else \
+	    echo "Compilation of sac2c for LINUX_X86 failed!"; \
+	    echo "Unable to create LINUX_X86 distribution !"; \
+	    exit 1; \
+	  fi
+
+sac2c.for.OSF_ALPHA libsac.tar.for.OSF_ALPHA: 
+	@echo "**************************************************************"
+	@echo "*  Creating sac2c for OSF_ALPHA"
+	@echo "**************************************************************"
+	@ ping $(ALPHA_HOST) >/dev/null; \
+          if [ $${?} -ne 0 ]; then \
+            echo "Host $(ALPHA_HOST) is down !"; \
+            echo "Unable to create OSF_ALPHA distribution !"; \
             exit 1; \
           fi
+	(cd $(SAC2CDIR); $(MAKE) tar) 
+	rsh -l $(ALPHA_USER) $(ALPHA_HOST) 'rm -rf $(ALPHA_DIR); mkdir -p $(ALPHA_DIR)' 
+	rcp $(SAC2CDIR)/src.tar.gz $(ALPHA_USER)@$(ALPHA_HOST):$(ALPHA_DIR)
+	rsh -l $(ALPHA_USER) $(ALPHA_HOST) \
+	    'cd $(ALPHA_DIR);'       \
+	    'gunzip -f src.tar.gz;'  \
+	    'tar xvf src.tar;'       \
+	    'chmod -R u+w *;'        \
+	    'touch src/*/*;'         \
+	    '$(ALPHA_MAKE) deps;'    \
+	    '$(ALPHA_MAKE) distrib_product OS=OSF_ALPHA'
+	rcp $(ALPHA_USER)@$(ALPHA_HOST):$(ALPHA_DIR)/sac2c ./sac2c.for.OSF_ALPHA
+	rsh -l $(ALPHA_USER) $(ALPHA_HOST)   \
+	    'cd $(ALPHA_DIR)/src/runtime;'  \
+	    'tar cvfh libsac.tar libsac*.a'
+	rcp $(ALPHA_USER)@$(ALPHA_HOST):$(ALPHA_DIR)/src/runtime/libsac.tar ./libsac.tar.for.OSF_ALPHA
+	@ if [ $${?} -eq 0 ]; then  \
+	    rsh -l $(ALPHA_USER) $(ALPHA_HOST) 'rm -rf $(ALPHA_DIR)'; \
+	  else \
+	    echo "Compilation of sac2c for OSF_ALPHA failed!"; \
+	    echo "Unable to create OSF_ALPHA distribution !"; \
+	    exit 1; \
+	  fi
 
 $(SRCTARGETDIR)/SAC-$(VERSION)-$(DATE).tar.gz: $(PACKAGES) $(FILES) src.tar.gz
 	@echo "**************************************************************"
@@ -229,4 +281,3 @@ new:
 allnew:
 	$(MAKE) clean
 	$(MAKE)
-
